osx_image: xcode8.2
language: objective-c

install:
  - ./install_swiftlint.sh

script:
- swiftlint
- xcodebuild test -project Currier.xcodeproj -scheme Currier -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7'
