osx_image: xcode10.3
language: objective-c

install:
- gem install cocoapods
- ./install_swiftlint.sh

script:
- pod lib lint Currier.podspec
- swiftlint

- xcodebuild test -project Currier.xcodeproj -scheme Currier-iOS -destination 'platform=iOS Simulator,OS=latest,name=iPhone 8'
- xcodebuild test -project Currier.xcodeproj -scheme Currier-macOS -destination 'platform=macOS,arch=x86_64' 
- xcodebuild test -project Currier.xcodeproj -scheme Currier-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p'

- xcodebuild -project Currier.xcodeproj -scheme Currier-watchOS